### ISSUE TITLE
Polybrush obsolete warnings in the console upon opening project

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#1]
Open the latest pull of the 3D Game Kit in 2019.1.0b9

Upon opening the project you'll see 3 warnings in the console:

<img width="1335" alt="image" src="https://user-images.githubusercontent.com/29916701/55230515-f2a2ed00-5217-11e9-9ea3-cea25b110a61.png">

Upgrading to a newer version of Polybrush from the asset store didn't fix this issue.

**Comment by UnityGuillaume** [comment]
@Jacekpapapolski there is a package polybrush now it look like...but I wouldn't upgrade. It may not grab it's setting or aplette in the same place etc... so to avoid any problem, I would say let's keep the warning? 

We should make a note somewhere to take a look when we have some time to upgrade to use the Polybrush package instead of the asset store version embedded in the project.
