### ISSUE TITLE
[Mac] Deleted cube reappears, 2020.2.0b13 

### ISSUE THREAD

**Issue by jesusrubiom** [Unity-Technologies/Gamekit3D#17]
**Description**

A cube that I built through the ProBuilder window, reappears when I enter Play mode after I have already deleted it.

**Steps to reproduce**

Open the project in 2020.2.0b13 in a Mac OS

Open the Scene "_TemplateScene"

Go to Tools > ProBuilder >ProBuilder Window

Click the + and add a cube

Click Build Cube

Delete the Cube and enter Play mode

Exit Play mode and you will see the deleted Cube reappear in your Scene
Part1
![3dgamekit-bug-cube1](https://user-images.githubusercontent.com/67921724/100696590-b9a21080-3348-11eb-87b2-e9bf127dc10a.gif)
Part 2
![Gamekit3d-bug-cube2](https://user-images.githubusercontent.com/67921724/100696755-24ebe280-3349-11eb-987f-8824b4ee27cd.gif)
Part 3
![Gamekit3d-bug-cube3](https://user-images.githubusercontent.com/67921724/100696811-42b94780-3349-11eb-8479-4b68ace6dcc0.gif)

**Comment by Jacekpapapolski** [comment]
I couldn't reproduce on Windows.

If the cube is still blue when deleted, it is expected for it to come back however due to how ProBuilder functions. You have to press the "Build" button and ensure the cube (or any other shape) goes from blue to white - then the shape does not re-appear on entering/exiting play mode
