### ISSUE TITLE
[Mac] Rock prefabs missing other half in the Scene, 2020.2

### ISSUE THREAD

**Issue by jesusrubiom** [Unity-Technologies/Gamekit3D#18]
**Description**

Half of the CliffBig01 prefab is missing when added to the Scene.

**Steps to reproduce**

Open project in 2020.2.0b13 on a Mac OS

Go to Assets > 3DGamekit > Prefabs > Environment > Rock

Drag and drop the CliffBig01 prefab into the Scene

Rotate the prefab and half is missing
<img width="1239" alt="Screen Shot 2020-11-30 at 8 38 07 PM" src="https://user-images.githubusercontent.com/67921724/100698662-dbea5d00-334d-11eb-8d23-507a9530f8ef.png">

Seems like this is happening to the following prefabs:
CliffBig01, CliffBig02, CliffBig03, CliffEdge01, CliffEdge02, CliffEdge03, CliffEdge04, RockLedge01, RockLedge02

**Comment by Jacekpapapolski** [comment]
This is expected and due to optimization. 

I am not an artist so can't explain it fully, but these rocks are only ever visible for the player from one direction. Since these are high quality, detailed assets, it would be a huge use of resources to render them on both sides. Therefore, they are only rendered the way the player will be looking, saving on processing power and providing a performance increase.

(as far as my non-game developer artist brain understands it :))
