### ISSUE TITLE
Ellen doesn't respawn when she falls into the water

### ISSUE THREAD

**Issue by Jacekpapapolski** [Unity-Technologies/Gamekit3D#7]
Open up Level1 of the 3DGK and press Play

Once in Play Mode walk Ellen over to the water and jump into it 

Ellen will play her death animation and lie down at the bottom of the waterbed, lifeless and sad

She will stay there for all eternity, while the player can move the camera to observe this sad, heartbreaking moment from any angle

At this point you have to exit play mode as there's nothing else you can do.

**Comment by UnityGuillaume** [comment]
@Jacekpapapolski is the game running slow when that happen? If I replace the material of the water (that seem to break badly in 19.1 because the FPS drop a LOT when using the water material) with a default material, she respawn perfectly. Can you confirm? If yes that's probably something to do with low FPS, will investigate.

**Comment by Jacekpapapolski** [comment]
Yeah seems like you're right... Ellen respawned correctly on Windows version which was running much faster/smoother
I did leave the mac version running with her in the water for quite a long time (~40ish seconds?) so it seems like the low FPS will prevent the respawn from happening

**Comment by UnityGuillaume** [comment]
Remade the water mesh in 8622b2d : had broken painting vertex that were destroying performance, now run smoothly and seem to fix that respawn bug
